My portfolio
Goodluck5956/My-portfolio pull request #1
Opened 2021-07-14 21:31 UTC by Goodluck5956

### Mobile version skeleton setup

- code divided into sections like

1. header part which contains both the logo and hamburger section
2. the title part
3. content part which contains the detail of the page
4. the connecting sections and the links to navigate

2021-07-14 22:40 UTC, AshakaE requested changes
### Hi @Goodluck5956 , 

Good job so far! You have used the proper semantic HTML tags, However there are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


# Required Changes ♻️
Please try as much as possible to mimic the design from the template, your project is missing some features (font weight, font size, colors and positioning) 

1. Placing of the background image appropriately
2. Works section of the portfolio is missing, please add it


_Check the comments under the review._

###  Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2021-07-14 22:40 UTC, AshakaE commented on index.html
> +    <main>
- [ ] Elements within the `main` tag are styled and positioned using CSS grids, kindly update it.
- [ ] The background decoration is missing, please update it

2021-07-15 23:57 UTC, Emmyn5600 requested changes
## STATUS: Changes Requested :recycle:

Hi @Goodluck5956 

Good job so far!:clap::clap:
You have done well in implementing the changes requested by the previous code reviewer :clap:, However, there are some issues that you still need to work on to go to the next project but you are almost there!:muscle:

##  Required Changes:writing_hand:

* Please add a descriptive Readme file for more details related to your project.

**_Check the comments under the review._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-07-15 23:57 UTC, Emmyn5600 commented on index.html
> +
- [ ] The hamburger button is on the right, and has a nav tag, please hamburger button instead of menu bar paragraph and logo or your name instead of symbol
![menuu](https://user-images.githubusercontent.com/55635977/125871829-368d69f2-e096-42ff-ba64-2a9c4f1b56d2.png)

2021-07-15 23:57 UTC, Emmyn5600 commented on index.html
> +    <h2 class="main-heading">I’m Lucky<br>
- [ ] Use h1 tag for `I'm lucky` heading instead of h2

2021-07-15 23:57 UTC, Emmyn5600 commented on index.html
> +    </body>
- [ ] The section uses the font and colors (background and font) defined for the template, kindly implement this as it was requested by the previous reviewer as well as to meet with the requirements.

2021-07-17 21:33 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi ll,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2021-07-17 21:53 UTC, arslanbisharat approved these changes
This project is already approved

2021-07-17 21:56 UTC, merged